runtime: python27
threadsafe: true
handlers:
  - url: /index\.html
    static_files: index.html
    upload: index.html

  - url: /assets
    static_dir: assets

  - url: /
    static_files: index.html
    upload: index.html